CON-50: Pick a different validator key for each node.

diff --git a/docker/Makefile b/docker/Makefile
--- a/docker/Makefile
+++ b/docker/Makefile
@@ -1,14 +1,36 @@
+# Don't remove directories created as dependencies.
+.SECONDARY:
 
-# Create a new node project by linking to the template docker-complse.yml file.
+# Create a new node environment by linking to the template docker-complse.yml file.
 node-%:
 	$(eval N = $*)
+
+	$(eval KEY_FILE_COUNT = $(shell find .casperlabs -type f -name *.sk | wc -l))
+	[ "$(N)" -lt "$(KEY_FILE_COUNT)" ] || (echo "Can't find keyfile for node-$(N)" && exit 1)
+	$(eval KEY_FILE = $(shell find .casperlabs -type f -name *.sk | sort | tail -n +$$((1+$(N))) | head -n 1))
+
 	mkdir node-$(N)
+	$(eval ENV = node-$(N)/.env)
+
+	@# Create an .env file to hold template variables for docker-compose.
+	echo NODE_NUMBER=$(N) > $(ENV)
+
+	@# The name of the file is the public key. Content is the private key.
+	echo VALIDATOR_PUBLIC_KEY=$(shell echo "$(KEY_FILE)" | awk -F '[/.]' '{print $$4}') >> $(ENV)
+	echo VALIDATOR_PRIVATE_KEY=$(shell cat "$(KEY_FILE)") >> $(ENV)
+
+	@# Link Dockerfile so we can change it and reapply.
 	ln -s ${PWD}/template/docker-compose.yml node-$(N)/docker-compose.yml
 
-up/node-%: node-%
-	docker-compose -f node-$*/docker-compose.yml up -d
+# Start node.
+node-%/up: node-%
+	@# Go into the directory to pick up values from .env
+	cd node-$* && docker-compose up -d
 
-down/node-%:
-	$(eval N = $*)
-	docker-compose -f node-$(N)/docker-compose.yml down
-	rm -rf node-$(N)
+# Tear down node.
+node-%/down:
+	[ -d node-$* ] && cd node-$* && docker-compose down || exit 0
+	rm -rf node-$*
+
+# Remove all node-N environments.
+down: $(shell find . -type d -name "node-*" | awk -F '/' '{print $$2"/down"}')
